backend:
  name: git-gateway
  branch: main

editor:
  preview: false

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "jobs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Jobs" # Used in the UI, ie.: "New Post"
    folder: "site/content/jobs" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
